services:
  - type: web
    name: ai-knowledge-ui
    runtime: static
    buildCommand: npm install && npm run build -- --configuration=render --base-href=/
    publishDir: dist/ai-knowledge-ui
    plan: free
